RAVIKIRAN/14_OCT_2014_AJAX/student/config/routes.rb
Rails.application.routes.draw do
  get 'students/start'
  root 'students#start'
  get 'students/stud_insert_form'
  post 'students/student_save'
  get 'students/stud_show_form'
  get 'students/stud_update_form'
  patch 'students/student_update'
  delete 'students/student_delete'

end

RAVIKIRAN/14_OCT_2014_AJAX/student/app/models/mark.rb
class Mark < ActiveRecord::Base
end

RAVIKIRAN/14_OCT_2014_AJAX/student/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def stud_insert_form
  	@s=Mark.new
  end

  def student_save
  	@s=Mark.new(sparams)
  	@s.save
  	redirect_to students_start_path
  end

  def stud_show_form
  	@ss=Mark.all
  end

  def stud_update_form
  	@s=Mark.find(params[:format])
  end

  def student_update
  	@s=Mark.find (params[:id])
    @s.update(sparams)
    @s=Mark.all
    redirect_to students_start_path
  end
  def student_delete
  	@s=Mark.find(params[:format])
  	@s.destroy
  	redirect_to students_start_path
  end
  private
  def sparams
  	params.require(:mark).permit(:s_name,:marks)
  end
end

RAVIKIRAN/14_OCT_2014_AJAX/student/app/helpers/students_helper.rb
module StudentsHelper
end

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/_stud_insert_form.html.erb
<h1> ADD STUDENT DETAILS </h1>
<%= form_for @s, url:{action: 'student_save'} do |f| %>
<table border=1>
	<tr>
		<td> <%= f.label :'student name :' %> </td>
		<td> <%= f.text_field :s_name %> </td>
	</tr>

	<tr>
		<td> <%= f.label :'marks :' %> </td>
		<td> <%= f.text_field :marks %> </td>
	</tr>
</table> <br>
<%= f.submit :"INSERT" %>
<%end%>

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/_stud_show_form.html.erb
<h6> MARKS DETAILS </h6>
<table border=2>
	<tr>
		<th> STUDENT NAME </th>
		<th> MARKS </th>
	</tr>
	<% @ss.each do |f| %>
	<tr>
		<td><%= f.s_name %></td>
		<td><%= f.marks %></td>
		<td><%= link_to 'UPDATE',students_stud_update_form_path(f),remote:true%></td>
        <td><%= link_to 'DELETE', students_student_delete_path(f),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
	</tr>
	<%end%>
</table>

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/_stud_update_form.html.erb
<h4>UPDATE DETAILS</h4>
<%= form_for @s, url:{action: 'student_update',id:@s.id} do |f| %>
<table border=1>
	<tr>
		<td> <%= f.label :'student name :' %> </td>
		<td> <%= f.text_field :s_name %> </td>
	</tr>

	<tr>
		<td> <%= f.label :'marks :' %> </td>
		<td> <%= f.text_field :marks %> </td>
	</tr>
</table> <br>
<%= f.submit :"UPDATE" %>
<%end%>

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/start.html.erb
<h1>STUDENT CRUD OPERATION USING AJAX</h1>

<%= link_to 'INSERT STUDENT DETAILS',students_stud_insert_form_path,remote:true%><br>

<%= link_to 'SHOW STUDENT DETAILS',students_stud_show_form_path,remote:true%><br>

<div id="insert"></div>
<div id="show"></div>
<div id="update"></div>

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/stud_insert_form.js.erb
$('#insert').html("<%=j render 'stud_insert_form'%>")

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/stud_show_form.js.erb
$('#show').html("<%=j render 'stud_show_form'%>")

RAVIKIRAN/14_OCT_2014_AJAX/student/app/views/students/stud_update_form.js.erb
$('#update').html("<%=j render 'stud_update_form'%>")