Ameya/14-Oct/ajaxdemo/config/routes.rb
Rails.application.routes.draw do
  get 'personalinfos/index'
  root 'personalinfos#new'
  resources :personalinfos

end

Ameya/14-Oct/ajaxdemo/app/models/personalinfo.rb
class Personalinfo < ActiveRecord::Base
end

Ameya/14-Oct/ajaxdemo/app/controllers/personalinfos_controller.rb
class PersonalinfosController < ApplicationController
  def index
  	@pers=Personalinfo.all
  end

  def new
  	@per=Personalinfo.new
  	 	@pers=Personalinfo.all
  end

  def create
  	@per=Personalinfo.create(personal_params)
  	@pers=Personalinfo.all
  end

  def edit
  	@per=Personalinfo.find(params[:id])
  end

  def update
  	@per=Personalinfo.find(params[:id])
  	@per.update(personal_params)
  	@pers=Personalinfo.all
  end

  def destroy
  	@per=Personalinfo.find(params[:id])
  	@per.destroy
  	@pers=Personalinfo.all
  end

  private
  	def personal_params
  		params.require(:personalinfo).permit!
  	end
end

Ameya/14-Oct/ajaxdemo/app/helpers/personalinfos_helper.rb
module PersonalinfosHelper
end

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/_edit.html.erb
<div class="modal-dialog">
  <div class='modal-content'>
    <div class='modal-body'>
      <%= form_for @per, url:{action: 'update', id:@per.id}, remote:true do |f| %>

      <table>
        <tr>
          <td><%= f.label :'First Name' %></td>
          <td><%= f.text_field :first_name %></td>
        </tr>
    
        <tr>
          <td><%= f.label :'Last Name' %></td>
          <td><%= f.text_field :last_name %></td>
        </tr>

        <tr>
          <td><%= f.label :'Age' %></td>
          <td><%= f.text_field :age %></td>
        </tr>

        <tr>
          <td><%= f.label :'Phone No.' %></td>
          <td><%= f.text_field :ph_no %></td>
        </tr>

        <tr>
          <td colspan="2"><%= f.submit :'UPDATE' %></td>
        </tr>
      </table>
    <% end %>
  
    </div>
  </div>
</div>

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/_index.html.erb
<%= form_for @per, url:{action: 'create'}, remote:true do |f| %>

  <table>
    <tr>
    	<td><%= f.label :'First Name' %></td>
    	<td><%= f.text_field :first_name %></td>
  	</tr>
    
    <tr>
    	<td><%= f.label :'Last Name' %></td>
    	<td><%= f.text_field :last_name %></td>
  	</tr>

    <tr>
    	<td><%= f.label :'Age' %></td>
    	<td><%= f.text_field :age %></td>
  	</tr>

  	<tr>
    	<td><%= f.label :'Phone No.' %></td>
    	<td><%= f.text_field :ph_no %></td>
  	</tr>

    <tr>
    	<td colspan="2"><%= f.submit :'SAVE' %></td>
    </tr>
  </table>
<% end %>

<table border="1">
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Age</th>
		<th>Phone No.</th>
	</tr>

	<%@pers.each do |f|%>
		<tr>
			<td><%=f.first_name%></td>
			<td><%=f.last_name%></td>
			<td><%=f.age%></td>
			<td><%=f.ph_no%></td>
			<td><%=link_to 'Edit', edit_personalinfo_path(f), remote:true%></td>
			<td><%=link_to 'Delete', personalinfo_path(f), remote:true, method: :delete, data: {confirm: 'Are you sure?'}%></td>
		</tr>
	<%end%>
</table>

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/create.js.erb
$('#show').html("<%= j render 'index' %>")

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/destroy.js.erb
$('#show').html("<%= j render 'index' %>")

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/edit.js.erb
$('#myModal').html("<%= j render 'edit'%>")
$('#myModal').modal('show')

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/new.html.erb
<div id="show">
<%=render 'index'%>
</div>

<div id="myModal" class="modal fade">
</div>

Ameya/14-Oct/ajaxdemo/app/views/personalinfos/update.js.erb
$('#show').html("<%= j render 'index'%>")
$('#myModal').modal('hide')